export interface StudentInfo {
  id?: number; // optional, auto-generated by DB
  student_number: string;
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  dob?: string; // YYYY-MM-DD
  age?: number;
  gender?: "Male" | "Female" | "Other";
  address?: string;
  nationality?: string;
  course_id: number;
  enrollment_date?: string; // YYYY-MM-DD
  intake?: string; // e.g. "Fall 2025"
  status?: "active" | "inactive" | "graduated" | "withdrawn";
  created_at?: string;
  updated_at?: string;
}

export interface User {
  id: number;                     // unique identifier
  email: string;                   // login email
  password_hash: string;           // hashed password (never store plain text!)
  username?: string;                   // optional display name
  role: "student" | "admin" | "staff"; // roles for access control
  created_at: string;              // timestamp (ISO string from DB)
  updated_at: string;    
  status:string;          // timestamp (ISO string from DB)
}

export interface StaffInfo {
  id?: number;                    // optional, auto-generated by DB
  staff_id: string;               // unique staff identifier (e.g., STF001)
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  mobile?: string;
  emergency_contact?: string;
  emergency_phone?: string;
  dob?: string;                   // YYYY-MM-DD
  age?: number;
  gender?: "Male" | "Female" | "Other";
  address?: string;
  city?: string;
  postal_code?: string;
  country?: string;
  nationality?: string;
  national_id?: string;           // National ID/Passport number
  
  // Employment Details
  employee_type?: "Full-Time" | "Part-Time" | "Contract" | "Visiting";
  position: string;               // Job title (e.g., Professor, Lecturer, Admin Officer)
  department: string;             // Department/Faculty
  office_location?: string;
  qualification?: string;         // Highest degree (PhD, MSc, BSc, etc.)
  specialization?: string;        // Field of expertise
  
  // Employment Dates
  hire_date?: string;             // YYYY-MM-DD
  contract_start?: string;        // YYYY-MM-DD
  contract_end?: string;          // YYYY-MM-DD (for contract staff)
  
  // Salary & Benefits
  salary?: number;
  salary_currency?: string;       // GBP, USD, etc.
  bank_account?: string;
  bank_name?: string;
  
  // Academic
  subjects_taught?: string;       // JSON array or comma-separated
  office_hours?: string;          // e.g., "Mon 2-4pm, Wed 10-12pm"
  
  // Status & Access
  status?: "active" | "inactive" | "on_leave" | "terminated" | "retired";
  access_level?: string;          // System access permissions
  
  // Additional
  photo_url?: string;             // Profile photo
  notes?: string;                 // Additional notes
  created_at?: string;
  updated_at?: string;
}

/*
  SQL TABLE CREATION for staff_info:
  
  CREATE TABLE staff_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(20),
    mobile VARCHAR(20),
    emergency_contact VARCHAR(100),
    emergency_phone VARCHAR(20),
    dob DATE,
    age INT,
    gender ENUM('Male', 'Female', 'Other'),
    address TEXT,
    city VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    nationality VARCHAR(100),
    national_id VARCHAR(100),
    
    employee_type ENUM('Full-Time', 'Part-Time', 'Contract', 'Visiting'),
    position VARCHAR(150) NOT NULL,
    department VARCHAR(150) NOT NULL,
    office_location VARCHAR(100),
    qualification VARCHAR(100),
    specialization VARCHAR(200),
    
    hire_date DATE,
    contract_start DATE,
    contract_end DATE,
    
    salary DECIMAL(10,2),
    salary_currency VARCHAR(10) DEFAULT 'GBP',
    bank_account VARCHAR(100),
    bank_name VARCHAR(100),
    
    subjects_taught TEXT,
    office_hours TEXT,
    
    status ENUM('active', 'inactive', 'on_leave', 'terminated', 'retired') DEFAULT 'active',
    access_level VARCHAR(50),
    
    photo_url VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_staff_id (staff_id),
    INDEX idx_email (email),
    INDEX idx_department (department),
    INDEX idx_status (status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/