// This are the student info for Regsiterd Students.
export interface StudentInfo {
  id?: number; // optional, auto-generated by DB
  student_number: string;
  first_name: string;
  middle_name?: string;
  last_name: string;
  email: string;
  phone?: string;
  dob?: string; // YYYY-MM-DD
  age?: number;
  gender?: "Male" | "Female" | "Other";
  address?: string;
  nationality?: string;
  passport_id?: string;
  blood_group?: string;
  course_id: number;
  enrollment_date?: string; // YYYY-MM-DD
  intake?: string; // e.g. "Fall 2025"
  previous_institution?: string;
  previous_qualification?: string;
  status?: "active" | "inactive" | "graduated" | "withdrawn";
  
  // Emergency Contact
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  emergency_contact_relationship?: string;
  
  // Parent/Guardian Information
  parent_guardian_name?: string;
  parent_guardian_phone?: string;
  parent_guardian_email?: string;
  
  // Medical Information
  medical_conditions?: string;
  
  created_at?: string;
  updated_at?: string;
}

export interface User {
  id: number;                     // unique identifier
  email: string;                   // login email
  password_hash: string;           // hashed password (never store plain text!)
  username?: string;                   // optional display name
  role: "student" | "admin" | "staff" | "super_admin" | "lecturer" | "agent"; // roles for access control
  reference_id?: string;           // student_number or staff_id for linking to respective tables
  created_at: string;              // timestamp (ISO string from DB)
  updated_at: string;    
  status: string;                  // active, inactive, suspended
}

export interface StaffInfo {
  id?: number;                    // optional, auto-generated by DB
  staff_id: string;               // unique staff identifier (e.g., STF001)
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  mobile?: string;
  emergency_contact?: string;
  emergency_phone?: string;
  dob?: string;                   // YYYY-MM-DD
  age?: number;
  gender?: "Male" | "Female" | "Other";
  address?: string;
  city?: string;
  postal_code?: string;
  country?: string;
  nationality?: string;
  national_id?: string;           // National ID/Passport number
  
  // Employment Details
  employee_type?: "Full-Time" | "Part-Time" | "Contract" | "Visiting";
  position: string;               // Job title (e.g., Professor, Lecturer, Admin Officer)
  department: string;             // Department/Faculty
  office_location?: string;
  qualification?: string;         // Highest degree (PhD, MSc, BSc, etc.)
  specialization?: string;        // Field of expertise
  
  // Employment Dates
  hire_date?: string;             // YYYY-MM-DD
  contract_start?: string;        // YYYY-MM-DD
  contract_end?: string;          // YYYY-MM-DD (for contract staff)
  
  // Salary & Benefits
  salary?: number;
  salary_currency?: string;       // GBP, USD, etc.
  bank_account?: string;
  bank_name?: string;
  
  // Academic
  subjects_taught?: string;       // JSON array or comma-separated
  office_hours?: string;          // e.g., "Mon 2-4pm, Wed 10-12pm"
  
  // Status & Access
  status?: "active" | "inactive" | "on_leave" | "terminated" | "retired";
  access_level?: string;          // System access permissions
  
  // Additional
  photo_url?: string;             // Profile photo
  notes?: string;                 // Additional notes
  created_at?: string;
  updated_at?: string;
}

export interface OfqualEnrollment {
  // Primary Key
  id?: number;
  application_ref?: string;       // Auto-generated unique reference (e.g., OFQ2026-0001)
  
  // Section 1: Personal Details
  full_legal_name: string;
  date_of_birth: string;          // YYYY-MM-DD
  gender?: "Male" | "Female" | "Other" | "Prefer not to say" | "";
  nationality?: string;
  uln?: string;                   // Unique Learner Number (10 digits)
  address?: string;
  postcode?: string;
  email: string;
  telephone: string;
  
  // Section 2: Identification & Eligibility
  id_type: "Passport" | "Driving Licence" | "National ID Card" | "Other";
  right_to_study_uk?: "Yes" | "No" | "Not applicable (overseas learner)" | "";
  
  // Section 3: Qualification Details
  qualification_title: string;
  qualification_level: "Level 3" | "Level 4" | "Level 5" | "Level 6" | "Level 7" | "Level 8";
  awarding_organisation: "OTHM" | "QUALIFI";
  mode_of_study: "Classroom" | "Online" | "Blended" | "Distance Learning";
  proposed_start_date?: string;   // YYYY-MM-DD
  
  // Section 4: Entry Requirements & Prior Learning
  highest_qualification: string;
  relevant_work_experience?: string;
  english_proficiency?: "Native speaker" | "IELTS" | "Other evidence" | "";
  ielts_score?: string;
  
  // Section 5: Equality & Diversity Monitoring (Optional)
  has_disability?: "Yes" | "No" | "Prefer not to say";
  disability_details?: string;
  ethnic_origin?: "White" | "Asian" | "Black" | "Mixed" | "Other" | "Prefer not to say" | "";
  
  // Section 6: Reasonable Adjustments & Special Consideration
  requires_adjustments?: "Yes" | "No";
  adjustment_details?: string;
  consent_to_share?: boolean;
  
  // Section 7: Data Protection & GDPR Consent
  read_privacy_notice: boolean;
  consent_data_processing: boolean;
  
  // Section 8: Learner Declaration
  agree_to_policies: boolean;
  
  // Application Status & Processing
  application_status?: "pending" | "under_review" | "approved" | "rejected" | "enrolled" | "withdrawn";
  student_id?: string;            // Assigned after enrollment
  enrollment_date?: string;       // YYYY-MM-DD
  
  // Reviewer Notes
  reviewer_id?: number;
  reviewer_notes?: string;
  reviewed_at?: string;
  
  // Audit Trail
  ip_address?: string;
  user_agent?: string;
  submission_date?: string;
  created_at?: string;
  updated_at?: string;
}

export interface AcademicCalendar {
  id?: number;                     // optional, auto-generated by DB
  event_title: string;             // Name of the academic event
  event_type: "arrival" | "enrolment" | "teaching" | "assessment" | "vacation" | "resit" | "progression" | "supervision";
  entry_point: "january_2026" | "march_2026" | "september_2026" | "all";
  programme_level: string;         // All, Diploma (RQF Level 4/5), BSc, MSc, PhD
  start_date: string;              // YYYY-MM-DD
  end_date: string;                // YYYY-MM-DD
  description?: string;            // Detailed description
  location?: string;               // Physical or online location
  
  // UKVI Compliance & Requirements
  is_mandatory: boolean;           // Whether attendance is mandatory
  ukvi_monitored: boolean;         // Whether UKVI monitors this event
  requires_attendance: boolean;    // Whether attendance tracking is required
  
  // Status & Display
  status: "upcoming" | "ongoing" | "completed" | "cancelled";
  display_order: number;           // Order for displaying events
  color_code: string;              // Hex color code for UI display (e.g., #3B82F6)
  
  created_at?: string;
  updated_at?: string;
}

// For Applications database
export type ApplicationStatus = 
    | 'pending'
    | 'under_review'
    | 'accepted'
    | 'rejected'
    | 'withdrawn'
    | 'deferred';

/**
 * Academic History Entry
 */
export interface AcademicHistoryEntry {
    institution: string;
    country: string;
    qualification: string;
    subject: string;
    start: string;
    end: string;
    grade: string;
}

/**
 * Employment History Entry
 */
export interface EmploymentHistoryEntry {
    employer: string;
    title: string;
    start: string;
    end: string;
}

/**
 * Reference Entry
 */
export interface ReferenceEntry {
    name: string;
    relationship: string;
    email: string;
    contact: string;
}

/**
 * Agent Information
 */
export interface AgentInformation {
    isAgentApplication: 'Yes' | 'No';
    agentName?: string;
    agentCompany?: string;
    agentEmail?: string;
    agentPhone?: string;
}

/**
 * Main Application/Lead Interface
 * Represents a single application record in the database
 */
export interface ApplicationLead {
    // Primary Key
    id: number;
    
    // SECTION 1: Personal Information
    firstName: string;
    middleName?: string;
    lastName: string;
    dateOfBirth: string; // Date in YYYY-MM-DD format
    gender: string;
    nationality: string;
    countryOfResidence: string;
    passportNumber?: string;
    
    // Contact Information
    email: string;
    phone: string;
    phoneCountry: string;
    address: string;
    city: string;
    state?: string;
    postalCode: string;
    country: string;
    
    // SECTION 2: Course Selection
    programme: string;
    intakeDate: string;
    studyMode: string;
    campus: string;
    levelOfStudy: string;
    
    // SECTION 3: Academic History (up to 3 entries)
    institutionName?: string;
    countryOfStudy?: string;
    qualification?: string;
    subject?: string;
    startDate?: string;
    endDate?: string;
    grade?: string;
    
    institutionName2?: string;
    countryOfStudy2?: string;
    qualification2?: string;
    subject2?: string;
    startDate2?: string;
    endDate2?: string;
    grade2?: string;
    
    institutionName3?: string;
    countryOfStudy3?: string;
    qualification3?: string;
    subject3?: string;
    startDate3?: string;
    endDate3?: string;
    grade3?: string;
    
    // SECTION 4: English Language Proficiency
    englishProficiencyType: string;
    testName?: string;
    testScore?: string;
    testDate?: string;
    
    // SECTION 5: Employment History (up to 2 entries)
    employerName?: string;
    jobTitle?: string;
    employmentStart?: string;
    employmentEnd?: string;
    
    employerName2?: string;
    jobTitle2?: string;
    employmentStart2?: string;
    employmentEnd2?: string;
    
    // SECTION 6: References (2 entries)
    refName?: string;
    refRelationship?: string;
    refEmail?: string;
    refContact?: string;
    
    refName2?: string;
    refRelationship2?: string;
    refEmail2?: string;
    refContact2?: string;
    
    // SECTION 7: Funding & Scholarships
    funding: string;
    applyScholarship?: 'Yes' | 'No';
    scholarshipName?: string;
    
    // SECTION 7B: Agent Information
    isAgentApplication: 'Yes' | 'No';
    agentName?: string;
    agentCompany?: string;
    agentEmail?: string;
    agentPhone?: string;
    
    // SECTION 8: Additional Information
    disability: 'Yes' | 'No';
    disabilityDetails?: string;
    criminalConviction: 'Yes' | 'No';
    convictionDetails?: string;
    additionalInfo?: string;
    
    // SECTION 9: Declaration
    declaration: 'Yes' | 'No';
    signatureName: string;
    signatureDate: string;
    
    // File Attachments
    filePaths?: string[]; // Array of file names
    
    // Application Status & Metadata
    status: ApplicationStatus;
    submissionDate: string; // DateTime in ISO format
    lastUpdated?: string; // DateTime in ISO format
    notes?: string;
    assignedTo?: string;
}

/**
 * Create Application DTO (Data Transfer Object)
 * Used when creating a new application (excludes auto-generated fields)
 */
export type CreateApplicationDTO = Omit<ApplicationLead, 'id' | 'submissionDate' | 'lastUpdated'>;

/**
 * Update Application DTO
 * Used when updating an existing application (all fields optional except id)
 */
export type UpdateApplicationDTO = Partial<ApplicationLead> & { id: number };

/**
 * Application List Item
 * Simplified interface for list views
 */
export interface ApplicationListItem {
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    programme: string;
    status: ApplicationStatus;
    submissionDate: string;
    isAgentApplication: 'Yes' | 'No';
    agentCompany?: string;
}

/**
 * Application Statistics
 */
export interface ApplicationStatistics {
    total: number;
    pending: number;
    underReview: number;
    accepted: number;
    rejected: number;
    withdrawn: number;
    deferred: number;
    byAgent: number;
    directApplications: number;
}

/**
 * Search/Filter Parameters
 */
export interface ApplicationSearchParams {
    status?: ApplicationStatus;
    programme?: string;
    fromDate?: string;
    toDate?: string;
    isAgentApplication?: 'Yes' | 'No';
    agentEmail?: string;
    searchTerm?: string; // For name/email search
    page?: number;
    limit?: number;
}

/**
 * Paginated Response
 */
export interface PaginatedApplications {
    data: ApplicationLead[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
}
// End of Applications database interfaces

/*
  SQL TABLE CREATION for academic_calendar:
  
  CREATE TABLE IF NOT EXISTS academic_calendar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    event_title VARCHAR(255) NOT NULL COMMENT 'Name of the academic event',
    event_type ENUM('arrival', 'enrolment', 'teaching', 'assessment', 'vacation', 'resit', 'progression', 'supervision') NOT NULL COMMENT 'Type of academic event',
    
    entry_point ENUM('january_2026', 'march_2026', 'september_2026', 'all') NOT NULL COMMENT 'Academic entry point',
    programme_level VARCHAR(100) DEFAULT 'All' COMMENT 'Programme level',
    
    start_date DATE NOT NULL COMMENT 'Event start date',
    end_date DATE NOT NULL COMMENT 'Event end date',
    
    description TEXT COMMENT 'Detailed description of the event',
    location VARCHAR(255) COMMENT 'Physical or online location',
    
    is_mandatory BOOLEAN DEFAULT false COMMENT 'Whether attendance is mandatory',
    ukvi_monitored BOOLEAN DEFAULT false COMMENT 'Whether UKVI monitors this event',
    requires_attendance BOOLEAN DEFAULT false COMMENT 'Whether attendance tracking is required',
    
    status ENUM('upcoming', 'ongoing', 'completed', 'cancelled') DEFAULT 'upcoming' COMMENT 'Current status of the event',
    display_order INT DEFAULT 0 COMMENT 'Order for displaying events',
    color_code VARCHAR(7) DEFAULT '#3B82F6' COMMENT 'Hex color code for UI display',
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_entry_point (entry_point),
    INDEX idx_event_type (event_type),
    INDEX idx_status (status),
    INDEX idx_dates (start_date, end_date),
    INDEX idx_programme_level (programme_level),
    INDEX idx_ukvi_monitored (ukvi_monitored),
    INDEX idx_display_order (display_order)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/

/*
  SQL TABLE CREATION for staff_info:
  
  CREATE TABLE staff_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(20),
    mobile VARCHAR(20),
    emergency_contact VARCHAR(100),
    emergency_phone VARCHAR(20),
    dob DATE,
    age INT,
    gender ENUM('Male', 'Female', 'Other'),
    address TEXT,
    city VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    nationality VARCHAR(100),
    national_id VARCHAR(100),
    
    employee_type ENUM('Full-Time', 'Part-Time', 'Contract', 'Visiting'),
    position VARCHAR(150) NOT NULL,
    department VARCHAR(150) NOT NULL,
    office_location VARCHAR(100),
    qualification VARCHAR(100),
    specialization VARCHAR(200),
    
    hire_date DATE,
    contract_start DATE,
    contract_end DATE,
    
    salary DECIMAL(10,2),
    salary_currency VARCHAR(10) DEFAULT 'GBP',
    bank_account VARCHAR(100),
    bank_name VARCHAR(100),
    
    subjects_taught TEXT,
    office_hours TEXT,
    
    status ENUM('active', 'inactive', 'on_leave', 'terminated', 'retired') DEFAULT 'active',
    access_level VARCHAR(50),
    
    photo_url VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_staff_id (staff_id),
    INDEX idx_email (email),
    INDEX idx_department (department),
    INDEX idx_status (status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/

// Staff Permissions Interface
export interface StaffPermissionRecord {
  id?: number;
  staff_id: string;
  pageId: string;
  page_name: string;
  canView: boolean;
  canEdit: boolean;
  canDelete: boolean;
  grantedBy: string;         // admin user_id who granted the permission
  grantedAt?: string;
  created_at?: string;
  updated_at?: string;
}

// Staff Activity Log (tracks who edited what)
export interface StaffActivityLog {
  id?: number;
  staff_id: string;
  staff_name: string;
  action: 'create' | 'update' | 'delete' | 'view';
  target_type: 'student' | 'application' | 'enrollment' | 'attendance' | 'grade' | 'other';
  target_id: string;         // ID of the record being modified
  target_name?: string;      // Name/description of the record
  changes?: string;          // JSON string of changes made
  ip_address?: string;
  user_agent?: string;
  created_at?: string;
}

/*
  SQL TABLE CREATION for staff_permissions:
  
  CREATE TABLE IF NOT EXISTS staff_permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id VARCHAR(50) NOT NULL,
    pageId VARCHAR(100) NOT NULL,
    page_name VARCHAR(200) NOT NULL,
    canView BOOLEAN DEFAULT false,
    canEdit BOOLEAN DEFAULT false,
    canDelete BOOLEAN DEFAULT false,
    grantedBy VARCHAR(50) NOT NULL COMMENT 'Admin user_id who granted permission',
    grantedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE KEY unique_staff_page (staff_id, pageId),
    INDEX idx_staff_id (staff_id),
    INDEX idx_pageId (pageId),
    FOREIGN KEY (staff_id) REFERENCES staff_info(staff_id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/

/*
  SQL TABLE CREATION for staff_activity_log:
  
  CREATE TABLE IF NOT EXISTS staff_activity_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id VARCHAR(50) NOT NULL,
    staff_name VARCHAR(200) NOT NULL,
    action ENUM('create', 'update', 'delete', 'view') NOT NULL,
    target_type ENUM('student', 'application', 'enrollment', 'attendance', 'grade', 'other') NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    target_name VARCHAR(255),
    changes TEXT COMMENT 'JSON string of changes',
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_staff_id (staff_id),
    INDEX idx_action (action),
    INDEX idx_target (target_type, target_id),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (staff_id) REFERENCES staff_info(staff_id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/