// This are the student info for Regsiterd Students.
export interface StudentInfo {
  id?: number; // optional, auto-generated by DB
  student_number: string;
  first_name: string;
  middle_name?: string;
  last_name: string;
  email: string;
  phone?: string;
  dob?: string; // YYYY-MM-DD
  age?: number;
  gender?: "Male" | "Female" | "Other";
  address?: string;
  nationality?: string;
  passport_id?: string;
  blood_group?: string;
  course_id: number;
  enrollment_date?: string; // YYYY-MM-DD
  intake?: string; // e.g. "Fall 2025"
  previous_institution?: string;
  previous_qualification?: string;
  status?: "active" | "inactive" | "graduated" | "withdrawn";
  
  // Emergency Contact
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  emergency_contact_relationship?: string;
  
  // Parent/Guardian Information
  parent_guardian_name?: string;
  parent_guardian_phone?: string;
  parent_guardian_email?: string;
  
  // Medical Information
  medical_conditions?: string;
  
  created_at?: string;
  updated_at?: string;
}

export interface User {
  id: number;                     // unique identifier
  email: string;                   // login email
  password_hash: string;           // hashed password (never store plain text!)
  username?: string;                   // optional display name
  role: "student" | "admin" | "staff" | "super_admin" | "lecturer" | "agent"; // roles for access control
  reference_id?: string;           // student_number or staff_id for linking to respective tables
  created_at: string;              // timestamp (ISO string from DB)
  updated_at: string;    
  status: string;                  // active, inactive, suspended
}

export interface StaffInfo {
  id?: number;                    // optional, auto-generated by DB
  staff_id: string;               // unique staff identifier (e.g., STF001)
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  mobile?: string;
  emergency_contact?: string;
  emergency_phone?: string;
  dob?: string;                   // YYYY-MM-DD
  age?: number;
  gender?: "Male" | "Female" | "Other";
  address?: string;
  city?: string;
  postal_code?: string;
  country?: string;
  nationality?: string;
  national_id?: string;           // National ID/Passport number
  
  // Employment Details
  employee_type?: "Full-Time" | "Part-Time" | "Contract" | "Visiting";
  position: string;               // Job title (e.g., Professor, Lecturer, Admin Officer)
  department: string;             // Department/Faculty
  office_location?: string;
  qualification?: string;         // Highest degree (PhD, MSc, BSc, etc.)
  specialization?: string;        // Field of expertise
  
  // Employment Dates
  hire_date?: string;             // YYYY-MM-DD
  contract_start?: string;        // YYYY-MM-DD
  contract_end?: string;          // YYYY-MM-DD (for contract staff)
  
  // Salary & Benefits
  salary?: number;
  salary_currency?: string;       // GBP, USD, etc.
  bank_account?: string;
  bank_name?: string;
  
  // Academic
  subjects_taught?: string;       // JSON array or comma-separated
  office_hours?: string;          // e.g., "Mon 2-4pm, Wed 10-12pm"
  
  // Status & Access
  status?: "active" | "inactive" | "on_leave" | "terminated" | "retired";
  access_level?: string;          // System access permissions
  
  // Additional
  photo_url?: string;             // Profile photo
  notes?: string;                 // Additional notes
  created_at?: string;
  updated_at?: string;
}

export interface AcademicCalendar {
  id?: number;                     // optional, auto-generated by DB
  event_title: string;             // Name of the academic event
  event_type: "arrival" | "enrolment" | "teaching" | "assessment" | "vacation" | "resit" | "progression" | "supervision";
  entry_point: "january_2026" | "march_2026" | "september_2026" | "all";
  programme_level: string;         // All, Diploma (RQF Level 4/5), BSc, MSc, PhD
  start_date: string;              // YYYY-MM-DD
  end_date: string;                // YYYY-MM-DD
  description?: string;            // Detailed description
  location?: string;               // Physical or online location
  
  // UKVI Compliance & Requirements
  is_mandatory: boolean;           // Whether attendance is mandatory
  ukvi_monitored: boolean;         // Whether UKVI monitors this event
  requires_attendance: boolean;    // Whether attendance tracking is required
  
  // Status & Display
  status: "upcoming" | "ongoing" | "completed" | "cancelled";
  display_order: number;           // Order for displaying events
  color_code: string;              // Hex color code for UI display (e.g., #3B82F6)
  
  created_at?: string;
  updated_at?: string;
}

/*
  SQL TABLE CREATION for academic_calendar:
  
  CREATE TABLE IF NOT EXISTS academic_calendar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    event_title VARCHAR(255) NOT NULL COMMENT 'Name of the academic event',
    event_type ENUM('arrival', 'enrolment', 'teaching', 'assessment', 'vacation', 'resit', 'progression', 'supervision') NOT NULL COMMENT 'Type of academic event',
    
    entry_point ENUM('january_2026', 'march_2026', 'september_2026', 'all') NOT NULL COMMENT 'Academic entry point',
    programme_level VARCHAR(100) DEFAULT 'All' COMMENT 'Programme level',
    
    start_date DATE NOT NULL COMMENT 'Event start date',
    end_date DATE NOT NULL COMMENT 'Event end date',
    
    description TEXT COMMENT 'Detailed description of the event',
    location VARCHAR(255) COMMENT 'Physical or online location',
    
    is_mandatory BOOLEAN DEFAULT false COMMENT 'Whether attendance is mandatory',
    ukvi_monitored BOOLEAN DEFAULT false COMMENT 'Whether UKVI monitors this event',
    requires_attendance BOOLEAN DEFAULT false COMMENT 'Whether attendance tracking is required',
    
    status ENUM('upcoming', 'ongoing', 'completed', 'cancelled') DEFAULT 'upcoming' COMMENT 'Current status of the event',
    display_order INT DEFAULT 0 COMMENT 'Order for displaying events',
    color_code VARCHAR(7) DEFAULT '#3B82F6' COMMENT 'Hex color code for UI display',
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_entry_point (entry_point),
    INDEX idx_event_type (event_type),
    INDEX idx_status (status),
    INDEX idx_dates (start_date, end_date),
    INDEX idx_programme_level (programme_level),
    INDEX idx_ukvi_monitored (ukvi_monitored),
    INDEX idx_display_order (display_order)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/

/*
  SQL TABLE CREATION for staff_info:
  
  CREATE TABLE staff_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(20),
    mobile VARCHAR(20),
    emergency_contact VARCHAR(100),
    emergency_phone VARCHAR(20),
    dob DATE,
    age INT,
    gender ENUM('Male', 'Female', 'Other'),
    address TEXT,
    city VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    nationality VARCHAR(100),
    national_id VARCHAR(100),
    
    employee_type ENUM('Full-Time', 'Part-Time', 'Contract', 'Visiting'),
    position VARCHAR(150) NOT NULL,
    department VARCHAR(150) NOT NULL,
    office_location VARCHAR(100),
    qualification VARCHAR(100),
    specialization VARCHAR(200),
    
    hire_date DATE,
    contract_start DATE,
    contract_end DATE,
    
    salary DECIMAL(10,2),
    salary_currency VARCHAR(10) DEFAULT 'GBP',
    bank_account VARCHAR(100),
    bank_name VARCHAR(100),
    
    subjects_taught TEXT,
    office_hours TEXT,
    
    status ENUM('active', 'inactive', 'on_leave', 'terminated', 'retired') DEFAULT 'active',
    access_level VARCHAR(50),
    
    photo_url VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_staff_id (staff_id),
    INDEX idx_email (email),
    INDEX idx_department (department),
    INDEX idx_status (status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/